language: python
sudo: false
python:
- '3.5'
install:
- pip install pipenv
- pipenv install --dev
script:
- pipenv run pytest --cov=./
deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true
    branch: master
  distributions: sdist
after_success:
- pipenv run codecov
